version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      args:
        - ALPINE_RUBY_VERSION
    volumes:
      - .:/app
    depends_on:
      - solr
    ports:
      - "3000:3000"
    environment:
      - SOLR_URL # Set via environment variable or use default defined in .env file
      - RAILS_VERSION # Set via environment variable or use default defined in .env file

  solr:
    environment:
      - SOLR_PORT # Set via environment variable or use default defined in .env file
      - SOLR_VERSION # Set via environment variable or use default defined in .env file
    image: "solr:${SOLR_VERSION}"
    volumes:
      - $PWD/lib/generators/blacklight/templates/solr/conf:/opt/solr/conf
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
